# ######################################## #
# ############ Directories ############### #
# ######################################## # 

data dir: 'data/raw'
images dir: 'images'
labels dir: 'labels'
test dir: 'test_images'

# ######################################## #
# ############ Training params ########### #
# ######################################## # 

seed: 100
batch size: 4