# ######################################## #
# ############ Directories ############### #
# ######################################## # 

data dir: 'data/raw'
images dir: 'images'
labels dir: 'labels'
test dir: 'test_images'

# ######################################## #
# ############ Training params ########### #
# ######################################## # 
experiment_number: 2
seed: 100
batch size: 4
lr: 0.0001
num epochs: 25
loss: bce  # dice

# ######################################## #
# ############ Evaluation params ######### #
# ######################################## # 
metrics: ['dice', 'pr-auc']
threshold: 0.4
predict_on: [test, train, val]