# ######################################## #
# ############ Directories ############### #
# ######################################## # 

data dir: 'data/raw'
images dir: 'images'
labels dir: 'labels'
test dir: 'test_images'

# ######################################## #
# ############ Training params ########### #
# ######################################## # 

seed: 100
batch size: 4
lr: 0.0001
num epochs: 30

# ######################################## #
# ############ Evaluation params ######### #
# ######################################## # 
metrics: ['dice', 'pr-auc']
threshold: 0.1