# ######################################## #
# ############ Directories ############### #
# ######################################## # 

data dir: 'data/raw'
image_folder: 'images'
label_folder: 'labels'
test_folder: 'test_images'
